### ISSUE TITLE
Ho-oh is missing

### ISSUE THREAD

**Issue by proegssilb** [ZeChrales/PogoAssets#1]
Ho-oh, number 250, is missing from the `decrypted_assets` folder. Expected files `pokemon_icon_250_00.png` and `pokemon_icon_250_00_shiny.png`.

**Comment by ryankane** [comment]
Why is it missing? It has not even been announced yet. Same goes for Delibird and Smeargle.

**Comment by JpDeathBlade** [comment]
The assets are downloaded from the Niantic server. These Pokemon don't exist serverside so the assets can't be downloaded.
