### ISSUE TITLE
Can you store the descripted text assets as .tsv?

### ISSUE THREAD

**Issue by JayTurnr** [ZeChrales/PogoAssets#10]
There's no downside to this as they'll still open in a text editor fine, and the file contents remain the exact same, however the upsides are:

- Programs like Excel will offer to open the file and show as a table
- GitHub displays csv/tsv files - https://help.github.com/articles/rendering-csv-and-tsv-data/

**Comment by JayTurnr** [comment]
I created a PR for this #11

**Comment by Ninadjeret** [comment]
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by ZeChrales** [comment]
Hey, I'm trying to keep files as they are in Unity. Please run some scripts when you git pull locally !

**Comment by JayTurnr** [comment]
That's fair!
