### ISSUE TITLE
Trimming/cropping empty space in icons?

### ISSUE THREAD

**Issue by galderz** [ZeChrales/PogoAssets#15]
Have you considered trimming mon pics to crop the empty space around them? I find it makes it easier to then fixate them in a specific height/width. This can easily be done with ImageMagick, e.g.

```
cd PogoAssets/pokemon_icons
for f in ./*.png; do
  convert "$f" -trim +repage "$f";
done
```

Example: [Before](https://github.com/ZeChrales/PogoAssets/blob/master/pokemon_icons/pokemon_icon_001_00_shiny.png) -> [After](https://www.dropbox.com/s/rf8uy99g7erpnvz/pokemon_icon_001_00_shiny.png?dl=0).

I can send a PR for the existing images if that's something you'd want. However, if you want this it might be something you run when extracting new assets and updating repo.

**Comment by JayTurnr** [comment]
I don't think he'll consider this, but it would be a good fork if maintained

**Comment by galderz** [comment]
Yeah, if it doesn't go in I was planning to do it for my own fork. Let's see :)

**Comment by ZeChrales** [comment]
Hi I want to keep files as raw output of unity encrypted files, you should run your own script in a secondary directory to get them trimmed then iconized etc !

**Comment by vidoardes** [comment]
@galderz is this something you were planning to do as a fork? I've been trying to this with XnView, Irfanview etc. but I always lose the transparency. 

I'm running a Windows box so I'd have to run up a virtual machine to run ImageMagick, which is fine but if you were going to do it anyway no need to duplicate effort

**Comment by galderz** [comment]
@vidoardes I decided against it in the end because I could not get the trimming to work well enough. I've seen other sites out there, they use CSS to zoom and pin each image depending on how they want to present it. For example, see [leeduck's shiny site] which underneath uses [css voodoo](https://github.com/Rplus/Pokemon-shiny/blob/master/style.css#L236-L786).

**Comment by JayTurnr** [comment]
> Yeah, if it doesn't go in I was planning to do it for my own fork. Let's see :)

Did you get around to forking?

**Comment by galderz** [comment]
@JayTurnr No, as I said above I could not get the trimming to work as I wanted, so didn't go down that route.

**Comment by PaulGolting** [comment]
@vidoardes - Thank you for this! I've been looking for something that provided this solution, so it is greatly appreciated!

**Comment by galderz** [comment]
@vidoardes Just got around to trying that yesterday and it worked great, thanks :)
