### ISSUE TITLE
Is the  Luxio(male) shiny image wrong?

### ISSUE THREAD

**Issue by Rplus** [ZeChrales/PogoAssets#16]
Shiny Luxio (male) image: https://github.com/ZeChrales/PogoAssets/blob/master/pokemon_icons/pokemon_icon_404_00_shiny.png
![image](https://user-images.githubusercontent.com/1808835/47593609-770fec00-d9aa-11e8-9e99-8ec46be58338.png)

-----

Shiny Luxio (female) image: https://github.com/ZeChrales/PogoAssets/blob/master/pokemon_icons/pokemon_icon_404_01_shiny.png
![image](https://user-images.githubusercontent.com/1808835/47593570-5fd0fe80-d9aa-11e8-8b86-7e6c69491e62.png)

**Comment by JayTurnr** [comment]
This looks like a bug within the game itself. My Shiny Luxio (Male) shows as non-shiny in the menu.

**Comment by ZeChrales** [comment]
yes error is sadly on niantic's side ...

**Comment by Rplus** [comment]
Thanks.
I find this screenshot: 
https://www.reddit.com/r/TheSilphRoad/comments/9pfhhl/shiny_luxio_appears_as_regular_sprite_in_pok%C3%A9mon/
![image](https://user-images.githubusercontent.com/1808835/47639200-a9cd0680-db9b-11e8-8de2-99bd0596cc8f.png)

:/
