### ISSUE TITLE
Pokémon and Move language files out of date

### ISSUE THREAD

**Issue by ryankane** [ZeChrales/PogoAssets#20]
Language files:

* https://github.com/ZeChrales/PogoAssets/blob/master/decrypted_assets/txt/pokemon.txt
* https://github.com/ZeChrales/PogoAssets/blob/master/decrypted_assets/txt/moves.txt

**Comment by M4d40** [comment]
As already said in other Issues, Niantic changed the way this data is stored.
You now can find the data within the merged files.

And no, he will not change the files in here, because this is the way it is originally stored in the game.

**Comment by ryankane** [comment]
Closing this, thanks.
