### ISSUE TITLE
Normal / Shiny Raichu with straw hat (form 10)

### ISSUE THREAD

**Issue by tlundse** [ZeChrales/PogoAssets#25]
Normal / Shiny Pikachu with straw hat (form 10) was commited Jul 22, but Raichu is missing.

**Comment by derigel23** [comment]
There is no Raichu with straw hat in the game

**Comment by tlundse** [comment]
It loses the hat on evolve...?

**Comment by PaulGolting** [comment]
@tlundse - No, Niantic doesn't allow Straw Hat Pikachu to evolve. It cannot be evolved in the game.

**Comment by tlundse** [comment]
Well, that was .. unexpected. Thanks for the explanation @PaulGolting.

Closing.
