### ISSUE TITLE
How to decrypt assets?

### ISSUE THREAD

**Issue by bleonard252** [ZeChrales/PogoAssets#3]
How do you decrypt your assets? If PMs existed on GitHub i would have sent you one

**Comment by ryankane** [comment]
I assume he is just hitting Niantic's server from an Android phone and grabbing the cached image files for the sprites that get served remotely?

**Comment by bleonard252** [comment]
Yes, but they are encrypted somehow.

**Comment by ZeChrales** [comment]
Sorry but that's not the purpose of this repo.
