### ISSUE TITLE
Shiny Bulbasaur family

### ISSUE THREAD

**Issue by ryankane** [ZeChrales/PogoAssets#4]
The sprites are missing.

* [decrypted_assets/pokemon_icon_001_00_shiny.png](https://github.com/ZeChrales/PogoAssets/blob/master/decrypted_assets/pokemon_icon_001_00_shiny.png)
* [decrypted_assets/pokemon_icon_002_00_shiny.png](https://github.com/ZeChrales/PogoAssets/blob/master/decrypted_assets/pokemon_icon_002_00_shiny.png)
* [decrypted_assets/pokemon_icon_003_00_shiny.png](https://github.com/ZeChrales/PogoAssets/blob/master/decrypted_assets/pokemon_icon_003_00_shiny.png)

**Comment by ZeChrales** [comment]
yes hello to you too
