### ISSUE TITLE
Wrong translation file

### ISSUE THREAD

**Issue by JayTurnr** [ZeChrales/PogoAssets#44]
On the German (de) translation file, it says the string for `profile_pokestops_visited` is `"PokéStops Visited:"` but in-game it shows up as `Besuchte PokéStops:`

`Besuchte PokéStops` or even just `Besuchte` doesn't appear in the translation file at all.

**Comment by JayTurnr** [comment]
The same problem exists for Italina (it) https://raw.githubusercontent.com/ZeChrales/PogoAssets/master/static_assets/txt/merged%20%2316.txt

**Comment by JayTurnr** [comment]
Found another issue in the Japanese (ja) file for the string `profile_total_xp` Ingame it comes through as トータルXP

**Comment by JayTurnr** [comment]
Found another issue in the Korean (ko) file for the `profile_pokestops_visited` string: in game it's `방문한 포켓스톱`

**Comment by ZeChrales** [comment]
switched to json

**Comment by JayTurnr** [comment]
> switched to json

Where?

**Comment by JayTurnr** [comment]
Please help, I can't find the json file. I've checked gamemaster.json but the actual translations don't appear to be in there.

**Comment by ZeChrales** [comment]
Github filtered them, no idea why. You can now find them in static_assets/txt
