### ISSUE TITLE
image assets for Gorebyss and Kecleon

### ISSUE THREAD

**Issue by ru7hl355** [ZeChrales/PogoAssets#8]
Hi, it looks like the repo is missing the assets for these 2, any chance you could add them?
thanks

**Comment by ZeChrales** [comment]
not yet in game !

**Comment by luissmg** [comment]
In defense of @ru7hl355, they are actually on the pokédex... Number 352 and 368.

**Comment by luissmg** [comment]
Those pokémon are in the in-game pokédex but I read that they are not available in it.

**Comment by M4d40** [comment]
I'm sorry i didn't want to sound rude/harsh.
It is just, that if it would be available ingame, he would have added it as soon as possible.
(Also it is similar to https://github.com/ZeChrales/PogoAssets/issues/1 )

**Comment by ru7hl355** [comment]
@M4d40 it’s ok, no doubt he will add them, I just didnt realise they weren’t in game yet... I saw them being viewed on his twitch feed and just assumed.
